### ISSUE TITLE
exec on firefox wont work

### ISSUE THREAD

**Issue by gabrielfsousa** [kubernetes/dashboard#3541]
##### Environment

```
Installation method: solo master
Kubernetes version: 1.13.2
Dashboard version: v1.10.1 
Operating system: centos 7.5

```

##### Observed result
when i click to exec a pod opens again the dashbord in dashboard

![image](https://user-images.githubusercontent.com/722744/51828685-0ac3c200-22e4-11e9-90fa-9978007b4988.png)

##### Expected result
show exec console

**Comment by PierluigiLenociAkelius** [comment]
Same here

**Comment by maciaszczykm** [comment]
Can you test it on Chrome and let us know if it works as expected?

**Comment by gabrielfsousa** [comment]
on chrome and opera works.

**Comment by floreks** [comment]
Which version of ff?

**Comment by gabrielfsousa** [comment]
64.0.2 (64-bit)

**Comment by PierluigiLenociAkelius** [comment]
64.0.2 (64 bit)

**Comment by jothimuruganm** [comment]
Hi Garbriel

Please check out the internet settings.
Follow steps from the following link.
https://support.mozilla.org/en-US/kb/firefox-cant-load-websites-other-browsers-can
Please update me if the issue is fixed.

**Comment by scorsair** [comment]
Same thing. Chome works. 
K8s 1.12.4, dashboard 1.10.1
FF: 64.0.2

**Comment by scorsair** [comment]
Same thing. Chome works. 
K8s 1.12.4, dashboard 1.10.1
FF: 64.0.2

@jothimuruganm still not working after that

**Comment by gabrielfsousa** [comment]
reverted my ff to 59.0.3 (64-bit) and on this version the exec works !!!

**Comment by floreks** [comment]
Closing then as this is ff related issue.

/close

**Comment by MMeent** [comment]
This is a bug in `hterm`, the library used for displaying the terminal screen, due to changed behaviour of Firefox. See https://bugs.chromium.org/p/chromium/issues/detail?id=918352

Can this issue be re-opened, so that when `hterm` has fixed their issue, that fix can be merged?

**Comment by maciaszczykm** [comment]
Can confirm that it doesn't work with my ff and hterm.org page.

**Comment by floreks** [comment]
@maciaszczykm should we close this as this is fixed on master? We are using now `xterm` instead of `hterm` and their demo (https://xtermjs.org/) works fine on my FF.

**Comment by maciaszczykm** [comment]
@floreks Agree.

/close

**Comment by 0312birdzhang** [comment]
Same thing again. Chome works.
K8s 1.11.7, dashboard v1.10.0 
Firefox: 67.0.2 (64 Bit)

**Comment by alectogeek** [comment]
+1

**Comment by blocknonip** [comment]
Still an issue as well.

Dashboard Version: v1.10.1
Git Commit: 50d59e985dfd97863a2f5ab5396ae049a2bb87d0 

macOS Firefox 67.0.4 (64-bit)

**Comment by aijanai** [comment]
+1
Dashboard Version: v1.8.3
Git Commit: ec1d7de4456e6a397c7f931f0a2bfc74a6ca2e9c

Firefox 68.0.1 (64 bit)
Ubuntu 16.04 (but same on MacOS Catalina)

**Comment by maciej-wakula-mobica** [comment]
Firefox 68.0.2 (64-bit), dashboard v1.10.1
Exec still not working.

**Comment by floreks** [comment]
How can it start working if you are still using the same version?

**Comment by maciaszczykm** [comment]
Use new beta to check if it's okay right now.

**Comment by joeblubaugh** [comment]
This is still broken for me on Firefox 70

**Comment by jacobreid** [comment]
Still broken.

**Comment by pierluigilenoci** [comment]
Continuing to comment that it doesn't work is useless. It has already been fixed in version 2 of the dashboard. 
Ref: https://github.com/kubernetes/dashboard/issues/3541#issuecomment-475189680
